name: Build Geode Mod

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

        - name: MacOS
          os: macos-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Server API
        run: |
          mkdir -p build/geode-deps/km7dev.server_api/
          curl -L -o ./km7dev.server_api.geode https://github.com/Kingminer7/server-api/releases/download/1.0.0/km7dev.server_api.geode
          7z x './km7dev.server_api.geode' '-o./build/geode-deps/km7dev.server_api'
          echo '{ "required": true }' > build/geode-deps/km7dev.server_api/geode-dep-options.json

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
      
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
