name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: Build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download Server API
        run: |
          mkdir -p ${{ github.workspace }}/cli-profile/geode/mods
          curl -L -o ${{ github.workspace }}/cli-profile/geode/mods/km7dev.server_api.geode https://github.com/Kingminer7/server-api/releases/download/1.0.2/km7dev.server_api.geode
          mkdir -p ${{ github.workspace }}/cli-profile/Contents/geode/mods
          curl -L -o ${{ github.workspace }}/cli-profile/Contents/geode/mods/km7dev.server_api.geode https://github.com/Kingminer7/server-api/releases/download/1.0.2/km7dev.server_api.geode

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          export-pdb: true
          target: ${{ matrix.config.target }}
          
  package:
    name: Package and release mod
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build
        name: Combine mods

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
